"""A database built from the models can actually search.

`search_vector` used to be a plain column that a migration backfilled and a
migration's trigger kept current. Both of those live inside `op.execute`, so
they exist only for a database that ran the revision — and the deployed
database was bootstrapped (`create_all` + `stamp head`), so no revision ever
did. The column existed, the GIN index existed, every row's vector was NULL,
and `@@` against a NULL vector is NULL rather than true.

The failure is completely silent: no error, no log line, an empty list that is
indistinguishable from "nothing matched". Customer product search, customer
vendor search, the vendor's search of their own catalogue and the rider's
vendor search were all dead, and no test in this suite could see it, because
nothing here touches a real database.

So the guard is static and it is about the *schema*: the definition has to live
in `Base.metadata`, where `create_all` will emit it, rather than in a migration
step that a bootstrapped database skips.
"""
import re

import pytest
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

from models.product_model import Product
from models.vendor_model import Vendor

# model column -> the source columns its vector must be built from
SEARCHABLE = {
    "Products": (Product, ("name", "description")),
    "Vendors": (Vendor, ("business_name", "location_address")),
}


@pytest.mark.parametrize("table", sorted(SEARCHABLE))
def test_the_search_vector_is_generated_by_the_database(table):
    """Not a plain column somebody has to remember to fill in."""
    model, _ = SEARCHABLE[table]
    column = model.__table__.c.search_vector
    assert column.computed is not None, (
        f"{table}.search_vector is a plain column again. A database built by "
        "scripts/bootstrap_database.py runs create_all and stamps the head, so "
        "a backfill or trigger that lives in a migration never executes and "
        "every row's vector stays NULL — which makes every search on this "
        "platform return an empty list, silently."
    )


@pytest.mark.parametrize("table", sorted(SEARCHABLE))
def test_the_generated_vector_is_stored_not_recomputed_per_row(table):
    """A virtual column could not be indexed, and the GIN index is the point."""
    model, _ = SEARCHABLE[table]
    assert model.__table__.c.search_vector.computed.persisted is True


@pytest.mark.parametrize("table", sorted(SEARCHABLE))
def test_create_all_emits_a_working_column(table):
    """The DDL `create_all` would run, which is what a new database gets."""
    model, sources = SEARCHABLE[table]
    ddl = str(CreateTable(model.__table__).compile(dialect=postgresql.dialect()))
    line = next(l for l in ddl.splitlines() if "search_vector" in l)
    assert "GENERATED ALWAYS AS" in line and "STORED" in line, line
    assert "to_tsvector" in line, line
    for source in sources:
        assert source in line, f"{table}.search_vector no longer covers {source}: {line}"


@pytest.mark.parametrize("table", sorted(SEARCHABLE))
def test_the_vector_is_still_indexed(table):
    """`@@` without the GIN index is a sequential scan of the whole catalogue."""
    model, _ = SEARCHABLE[table]
    gin = [
        index
        for index in model.__table__.indexes
        if index.kwargs.get("postgresql_using") == "gin"
        and any(c.name == "search_vector" for c in index.columns)
    ]
    assert gin, f"{table}.search_vector lost its GIN index"


def test_nothing_writes_to_a_generated_column():
    """Postgres refuses an explicit value for a generated column."""
    import pathlib

    root = pathlib.Path(__file__).resolve().parent.parent
    offenders = []
    for folder in ("routes", "services", "jobs"):
        for path in (root / folder).rglob("*.py"):
            for number, line in enumerate(path.read_text().splitlines(), 1):
                # An assignment, not a comparison and not a filter.
                if re.search(r"\.search_vector\s*=(?!=)", line):
                    offenders.append(f"{path.relative_to(root)}:{number}")
    assert not offenders, (
        "search_vector is generated by Postgres and cannot be assigned to: "
        + ", ".join(offenders)
    )
